name: 'Get Core Dependencies'
description: 'sets the node version & initializes core dependencies'
permissions:
  contents: read # to fetch code (actions/checkout)
runs:
  using: composite
  steps:
    - name: Checkout code
    uses: actions/checkout@v2

    - name: Set up Python
    uses: actions/setup-python@v2
    with:
        python-version: '3.9'  # Especifica la versión de Python adecuada

    - name: Install dependencies
    run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install cython
        pip install -r backend/requirements.txt

    - name: Migrate BD
    run: |
        cd backend
        python manage.py makemigrations
        python manage.py migrate