name: ci

on:
  push:
    branches: 
        - develop
    
jobs:
    createPullRequest:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
    
          - name: Make changes to pull request
            run: |
              # Realizar los cambios necesarios aquí, si es necesario
              date +%s > report.txt
              # Agregar todos los archivos modificados a la etapa de preparación del commit
              git add .
          
          - name: Update develop branch
            run: |
              git checkout develop
              git pull origin develop
    
          - name: Create Pull Request
            id: cpr
            uses: peter-evans/create-pull-request@v6
            with:
              token: ${{ secrets.PAT}}
              commit-message: Update report
              committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
              author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
              signoff: false
              branch: main  # Cambia la rama base a maintest
              delete-branch: false
              title: 'TEST SUCCESSFUL'
              body: |
                Update report
                - Updated with *today's* date
                - Auto-generated by [create-pull-request][1]
    
                [1]: https://github.com/peter-evans/create-pull-request
              labels: |
                report
                automated pr
              draft: false
              
