name: ci

on:
  push:
    branches:
      - develop

jobs:
  createPullRequest_Merge:
    runs-on: ubuntu-latest
    needs: test
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Aquí debes agregar los pasos necesarios para crear el pull request y realizar el merge
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Merge Changes From Develop
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: auto-merge/develop-to-main
          delete-branch: true
          title: 'Merge changes from develop to main'
          body: |
            This PR was created automatically because all tests and SonarCloud passed.
          base: main
          head: develop
          draft: false

      - name: Merge Pull Request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ steps.cpr.outputs.pull_number }},
              merge_method: 'merge'
            });
