name: main

on:
  push:
    branches: 
        - develop
  
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

  
jobs:



  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Include test.yml
        uses: ./.github/workflows/test.yml

        
    
  ci:
      name: ci
      needs: test
      if: ${{ success()}}
      runs-on: ubuntu-latest
      steps:
      - name: Include ci.yml
        uses: ./.github/workflows/ci.yml
    
    
