name: main
on:
  pull_request:
    branches:
      - develop
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Especifica la versi칩n de Python adecuada

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/App/appmanager/requirements.txt

      - name: Run Tests
        run: |
          python manage.py test backend/App/appmanager/tests.py

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Deshabilita los clones superficiales para un an치lisis m치s completo

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Necesario para obtener informaci칩n de la PR, si aplica
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Token de acceso de SonarCloud
